"""hydra/core/decoy.py — Generator for static decoy sites.

Provides distinct static sites (landing, blog, docs, status) to reduce active probing signals.
"""
from __future__ import annotations

import os
from pathlib import Path

DECOY_DIRS = {
    "naive": Path("/var/www/decoy-a"),
    "anytls": Path("/var/www/decoy-b"),
    "trusttunnel": Path("/var/www/decoy-c"),
    "hysteria2": Path("/var/www/decoy-hysteria2"),
}

DECOY_THEMES = {
    "naive": "landing",
    "anytls": "blog",
    "trusttunnel": "docs",
    "hysteria2": "status",
}


def ensure_decoy_site(plugin_name: str) -> Path:
    """Creates a decoy site for the specified plugin if it doesn't already exist.

    Returns the directory path.
    """
    site_dir = DECOY_DIRS.get(plugin_name)
    theme = DECOY_THEMES.get(plugin_name)
    if not site_dir or not theme:
        raise ValueError(f"Unknown plugin for decoy: {plugin_name}")

    if not (site_dir / "index.html").exists():
        _create_site(site_dir, theme)
    return site_dir


def _create_site(site_dir: Path, theme: str) -> None:
    """Generates the static site files under site_dir based on theme."""
    site_dir.mkdir(parents=True, exist_ok=True)
    (site_dir / "css").mkdir(exist_ok=True)
    (site_dir / "js").mkdir(exist_ok=True)
    (site_dir / "images").mkdir(exist_ok=True)

    # robots.txt
    (site_dir / "robots.txt").write_text(
        "User-agent: *\n"
        "Allow: /\n"
        f"Sitemap: https://example.com/sitemap.xml\n",
        encoding="utf-8"
    )

    # 1x1 favicon.ico placeholder
    (site_dir / "favicon.ico").write_bytes(
        b"\x00\x00\x01\x00\x01\x00\x01\x01\x00\x00\x01\x00\x18\x00"
        b"\x30\x00\x00\x00\x16\x00\x00\x00\x00\x00\x00\x00\x00\x00"
        b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
        b"\x00\x00\x00\x00\xff\xff\xff\x00\x00\x00\x00\x00"
    )

    if theme == "landing":
        _generate_landing(site_dir)
    elif theme == "blog":
        _generate_blog(site_dir)
    elif theme == "docs":
        _generate_docs(site_dir)
    elif theme == "status":
        _generate_status(site_dir)


def _generate_status(site_dir: Path) -> None:
    """Generate a small, plausible service-status site for Hysteria2 probes."""
    (site_dir / "index.html").write_text(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "  <meta name=\"description\" content=\"Northstar Cloud service status\">\n"
        "  <title>Northstar Cloud Status</title>\n"
        "  <link rel=\"icon\" href=\"favicon.ico\">\n"
        "  <link rel=\"stylesheet\" href=\"css/style.css\">\n"
        "</head>\n<body>\n"
        "  <main class=\"container\">\n"
        "    <header><div class=\"brand\">Northstar Cloud</div><span>Service Status</span></header>\n"
        "    <section class=\"summary\"><i></i><strong>All systems operational</strong>"
        "<p>No incidents reported.</p></section>\n"
        "    <section class=\"services\">\n"
        "      <div><span>Edge Network</span><b>Operational</b></div>\n"
        "      <div><span>Cloud API</span><b>Operational</b></div>\n"
        "      <div><span>Object Storage</span><b>Operational</b></div>\n"
        "      <div><span>Monitoring</span><b>Operational</b></div>\n"
        "    </section>\n"
        "    <footer>Northstar Cloud infrastructure status</footer>\n"
        "  </main>\n"
        "</body>\n</html>\n",
        encoding="utf-8",
    )
    (site_dir / "css" / "style.css").write_text(
        ":root{color-scheme:light;font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;"
        "color:#172033;background:#f5f7fb}*{box-sizing:border-box}body{margin:0}.container{"
        "width:min(760px,calc(100% - 32px));margin:64px auto}header{display:flex;align-items:center;"
        "justify-content:space-between;margin-bottom:28px;color:#657086}.brand{font-size:20px;font-weight:700;"
        "color:#172033}.summary,.services{background:#fff;border:1px solid #e3e8f1;border-radius:12px;"
        "box-shadow:0 8px 24px rgba(24,39,75,.05)}.summary{padding:26px 28px;margin-bottom:18px}"
        ".summary i{display:inline-block;width:11px;height:11px;border-radius:50%;background:#22a06b;"
        "margin-right:10px}.summary strong{font-size:18px}.summary p{margin:8px 0 0 25px;color:#718096}"
        ".services{padding:0 28px}.services div{display:flex;justify-content:space-between;padding:20px 0;"
        "border-bottom:1px solid #edf0f5}.services div:last-child{border:0}.services b{color:#16845a;"
        "font-size:14px}footer{text-align:center;color:#929bad;font-size:13px;margin-top:28px}"
        "@media(max-width:520px){.container{margin:28px auto}.services div{align-items:center;gap:16px}}\n",
        encoding="utf-8",
    )
    (site_dir / "status.json").write_text(
        '{"status":"operational","updated":null}\n', encoding="utf-8"
    )


def _generate_landing(site_dir: Path) -> None:
    # index.html
    (site_dir / "index.html").write_text(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "  <title>Apex Digital Agency | Home</title>\n"
        "  <link rel=\"stylesheet\" href=\"css/style.css\">\n"
        "  <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800&display=swap\" rel=\"stylesheet\">\n"
        "</head>\n<body>\n"
        "  <header class=\"navbar\">\n"
        "    <div class=\"container\">\n"
        "      <a href=\"index.html\" class=\"logo\">Apex<span>Digital</span></a>\n"
        "      <nav class=\"nav-links\">\n"
        "        <a href=\"index.html\" class=\"active\">Home</a>\n"
        "        <a href=\"about.html\">About Us</a>\n"
        "        <a href=\"contact.html\">Contact</a>\n"
        "      </nav>\n"
        "    </div>\n"
        "  </header>\n"
        "  <section class=\"hero\">\n"
        "    <div class=\"container\">\n"
        "      <h1>We Build Premium Digital Products</h1>\n"
        "      <p>Innovative web development, elegant UI/UX design, and result-oriented digital marketing strategies.</p>\n"
        "      <a href=\"contact.html\" class=\"btn\">Get In Touch</a>\n"
        "    </div>\n"
        "  </section>\n"
        "  <section class=\"services\">\n"
        "    <div class=\"container\">\n"
        "      <h2>Our Core Services</h2>\n"
        "      <div class=\"grid\">\n"
        "        <div class=\"card\">\n"
        "          <h3>Web Engineering</h3>\n"
        "          <p>Highly scalable, secure, and blazing fast web architectures tailored to your enterprise goals.</p>\n"
        "        </div>\n"
        "        <div class=\"card\">\n"
        "          <h3>UX/UI Design</h3>\n"
        "          <p>Beautiful, modern design interfaces crafted to maximize customer interaction and joy.</p>\n"
        "        </div>\n"
        "        <div class=\"card\">\n"
        "          <h3>Digital Growth</h3>\n"
        "          <p>Data-driven marketing and SEO optimization to boost your organic reach and conversion.</p>\n"
        "        </div>\n"
        "      </div>\n"
        "    </div>\n"
        "  </section>\n"
        "  <footer>\n"
        "    <p>&copy; 2026 Apex Digital Agency. All rights reserved.</p>\n"
        "  </footer>\n"
        "</body>\n</html>\n",
        encoding="utf-8"
    )

    # about.html
    (site_dir / "about.html").write_text(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "  <title>About Us | Apex Digital Agency</title>\n"
        "  <link rel=\"stylesheet\" href=\"css/style.css\">\n"
        "  <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800&display=swap\" rel=\"stylesheet\">\n"
        "</head>\n<body>\n"
        "  <header class=\"navbar\">\n"
        "    <div class=\"container\">\n"
        "      <a href=\"index.html\" class=\"logo\">Apex<span>Digital</span></a>\n"
        "      <nav class=\"nav-links\">\n"
        "        <a href=\"index.html\">Home</a>\n"
        "        <a href=\"about.html\" class=\"active\">About Us</a>\n"
        "        <a href=\"contact.html\">Contact</a>\n"
        "      </nav>\n"
        "    </div>\n"
        "  </header>\n"
        "  <section class=\"page-header\">\n"
        "    <div class=\"container\">\n"
        "      <h1>Who We Are</h1>\n"
        "      <p>A collective of designers, software engineers, and digital visionaries.</p>\n"
        "    </div>\n"
        "  </section>\n"
        "  <section class=\"content\">\n"
        "    <div class=\"container\">\n"
        "      <p>Founded in 2020, Apex Digital has quickly established itself as a premier agency for high-growth tech startups and established enterprises alike.</p>\n"
        "      <p>We pride ourselves on our meticulous approach, robust engineering guidelines, and absolute commitment to visual and technical quality.</p>\n"
        "    </div>\n"
        "  </section>\n"
        "  <footer>\n"
        "    <p>&copy; 2026 Apex Digital Agency. All rights reserved.</p>\n"
        "  </footer>\n"
        "</body>\n</html>\n",
        encoding="utf-8"
    )

    # contact.html
    (site_dir / "contact.html").write_text(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "  <title>Contact Us | Apex Digital Agency</title>\n"
        "  <link rel=\"stylesheet\" href=\"css/style.css\">\n"
        "  <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800&display=swap\" rel=\"stylesheet\">\n"
        "</head>\n<body>\n"
        "  <header class=\"navbar\">\n"
        "    <div class=\"container\">\n"
        "      <a href=\"index.html\" class=\"logo\">Apex<span>Digital</span></a>\n"
        "      <nav class=\"nav-links\">\n"
        "        <a href=\"index.html\">Home</a>\n"
        "        <a href=\"about.html\">About Us</a>\n"
        "        <a href=\"contact.html\" class=\"active\">Contact</a>\n"
        "      </nav>\n"
        "    </div>\n"
        "  </header>\n"
        "  <section class=\"page-header\">\n"
        "    <div class=\"container\">\n"
        "      <h1>Let's Connect</h1>\n"
        "      <p>Ready to start your next premium digital experience? Get in touch.</p>\n"
        "    </div>\n"
        "  </section>\n"
        "  <section class=\"contact-form-section\">\n"
        "    <div class=\"container\">\n"
        "      <form class=\"contact-form\" action=\"#\" method=\"POST\">\n"
        "        <label for=\"name\">Full Name</label>\n"
        "        <input type=\"text\" id=\"name\" name=\"name\" required placeholder=\"Jane Doe\">\n"
        "        \n"
        "        <label for=\"email\">Email Address</label>\n"
        "        <input type=\"email\" id=\"email\" name=\"email\" required placeholder=\"jane@example.com\">\n"
        "        \n"
        "        <label for=\"msg\">Project Scope</label>\n"
        "        <textarea id=\"msg\" name=\"msg\" rows=\"5\" placeholder=\"Tell us about your project...\"></textarea>\n"
        "        \n"
        "        <button type=\"submit\" class=\"btn\">Send Message</button>\n"
        "      </form>\n"
        "    </div>\n"
        "  </section>\n"
        "  <footer>\n"
        "    <p>&copy; 2026 Apex Digital Agency. All rights reserved.</p>\n"
        "  </footer>\n"
        "</body>\n</html>\n",
        encoding="utf-8"
    )

    # style.css
    (site_dir / "css" / "style.css").write_text(
        "body {\n"
        "  margin: 0;\n"
        "  font-family: 'Inter', sans-serif;\n"
        "  color: #333;\n"
        "  background: #fdfdfd;\n"
        "  line-height: 1.6;\n"
        "}\n"
        ".container {\n"
        "  width: 90%;\n"
        "  max-width: 1100px;\n"
        "  margin: 0 auto;\n"
        "}\n"
        ".navbar {\n"
        "  background: #fff;\n"
        "  border-bottom: 1px solid #eee;\n"
        "  padding: 1rem 0;\n"
        "}\n"
        ".navbar .container {\n"
        "  display: flex;\n"
        "  justify-content: space-between;\n"
        "  align-items: center;\n"
        "}\n"
        ".logo {\n"
        "  font-size: 1.5rem;\n"
        "  font-weight: 800;\n"
        "  color: #111;\n"
        "  text-decoration: none;\n"
        "}\n"
        ".logo span {\n"
        "  color: #0070f3;\n"
        "}\n"
        ".nav-links a {\n"
        "  margin-left: 1.5rem;\n"
        "  text-decoration: none;\n"
        "  color: #666;\n"
        "  font-weight: 600;\n"
        "  transition: color 0.2s;\n"
        "}\n"
        ".nav-links a:hover, .nav-links a.active {\n"
        "  color: #0070f3;\n"
        "}\n"
        ".hero {\n"
        "  padding: 8rem 0;\n"
        "  background: radial-gradient(circle at top right, #e3f2fd, #fff);\n"
        "  text-align: center;\n"
        "}\n"
        ".hero h1 {\n"
        "  font-size: 3rem;\n"
        "  margin: 0 0 1.5rem 0;\n"
        "  font-weight: 800;\n"
        "  color: #111;\n"
        "}\n"
        ".hero p {\n"
        "  font-size: 1.25rem;\n"
        "  color: #666;\n"
        "  max-width: 600px;\n"
        "  margin: 0 auto 2rem auto;\n"
        "}\n"
        ".btn {\n"
        "  background: #0070f3;\n"
        "  color: #fff;\n"
        "  padding: 0.75rem 1.5rem;\n"
        "  border-radius: 5px;\n"
        "  text-decoration: none;\n"
        "  font-weight: 600;\n"
        "  display: inline-block;\n"
        "  border: none;\n"
        "  cursor: pointer;\n"
        "  transition: background 0.2s;\n"
        "}\n"
        ".btn:hover {\n"
        "  background: #0051a8;\n"
        "}\n"
        ".services {\n"
        "  padding: 5rem 0;\n"
        "}\n"
        ".services h2 {\n"
        "  text-align: center;\n"
        "  margin-bottom: 3rem;\n"
        "  font-size: 2rem;\n"
        "}\n"
        ".grid {\n"
        "  display: grid;\n"
        "  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\n"
        "  gap: 2rem;\n"
        "}\n"
        ".card {\n"
        "  background: #fff;\n"
        "  border: 1px solid #eee;\n"
        "  padding: 2rem;\n"
        "  border-radius: 8px;\n"
        "  box-shadow: 0 4px 6px rgba(0,0,0,0.02);\n"
        "  transition: transform 0.2s, box-shadow 0.2s;\n"
        "}\n"
        ".card:hover {\n"
        "  transform: translateY(-5px);\n"
        "  box-shadow: 0 10px 15px rgba(0,0,0,0.05);\n"
        "}\n"
        "footer {\n"
        "  background: #111;\n"
        "  color: #888;\n"
        "  padding: 3rem 0;\n"
        "  text-align: center;\n"
        "  margin-top: 5rem;\n"
        "}\n"
        ".page-header {\n"
        "  background: #fafafa;\n"
        "  border-bottom: 1px solid #eee;\n"
        "  padding: 4rem 0;\n"
        "  text-align: center;\n"
        "}\n"
        ".page-header h1 {\n"
        "  margin: 0 0 1rem 0;\n"
        "}\n"
        ".page-header p {\n"
        "  color: #666;\n"
        "  margin: 0;\n"
        "}\n"
        ".content {\n"
        "  padding: 4rem 0;\n"
        "  max-width: 800px;\n"
        "  margin: 0 auto;\n"
        "}\n"
        ".contact-form-section {\n"
        "  padding: 4rem 0;\n"
        "}\n"
        ".contact-form {\n"
        "  max-width: 500px;\n"
        "  margin: 0 auto;\n"
        "  background: #fff;\n"
        "  padding: 2.5rem;\n"
        "  border: 1px solid #eee;\n"
        "  border-radius: 8px;\n"
        "}\n"
        ".contact-form label {\n"
        "  display: block;\n"
        "  margin-bottom: 0.5rem;\n"
        "  font-weight: 600;\n"
        "}\n"
        ".contact-form input, .contact-form textarea {\n"
        "  width: 100%;\n"
        "  padding: 0.75rem;\n"
        "  border: 1px solid #ccc;\n"
        "  border-radius: 4px;\n"
        "  margin-bottom: 1.5rem;\n"
        "  box-sizing: border-box;\n"
        "  font-family: inherit;\n"
        "}\n",
        encoding="utf-8"
    )


def _generate_blog(site_dir: Path) -> None:
    # index.html
    (site_dir / "index.html").write_text(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "  <title>TechBits | Insights on Modern Software</title>\n"
        "  <link rel=\"stylesheet\" href=\"css/style.css\">\n"
        "  <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&family=JetBrains+Mono&display=swap\" rel=\"stylesheet\">\n"
        "</head>\n<body>\n"
        "  <header class=\"blog-header\">\n"
        "    <div class=\"container\">\n"
        "      <a href=\"index.html\" class=\"blog-logo\">Tech<span>Bits</span></a>\n"
        "      <nav class=\"blog-nav\">\n"
        "        <a href=\"index.html\" class=\"active\">Stories</a>\n"
        "        <a href=\"about.html\">Author</a>\n"
        "      </nav>\n"
        "    </div>\n"
        "  </header>\n"
        "  <main class=\"container main-content\">\n"
        "    <section class=\"hero-post\">\n"
        "      <div class=\"meta\">Featured &bull; July 2026</div>\n"
        "      <h2><a href=\"post-1.html\">The Evolution of WebAssembly in the Cloud Native Stack</a></h2>\n"
        "      <p>How WebAssembly (Wasm) is evolving from a browser optimization tool into a lightweight, fast, and secure alternative for containerized workloads in production environments.</p>\n"
        "    </section>\n"
        "    <section class=\"recent-posts\">\n"
        "      <h3>Recent Articles</h3>\n"
        "      <div class=\"post-list\">\n"
        "        <article class=\"post-item\">\n"
        "          <div class=\"meta\">Design &bull; July 2, 2026</div>\n"
        "          <h4><a href=\"post-2.html\">Refining Micro-interactions in Clean Design Systems</a></h4>\n"
        "          <p>A deep dive into how subtle animations can delight users and drastically improve conversion and accessibility.</p>\n"
        "        </article>\n"
        "      </div>\n"
        "    </section>\n"
        "  </main>\n"
        "  <footer>\n"
        "    <p>&copy; 2026 TechBits. Built with absolute focus.</p>\n"
        "  </footer>\n"
        "</body>\n</html>\n",
        encoding="utf-8"
    )

    # about.html
    (site_dir / "about.html").write_text(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "  <title>About the Author | TechBits</title>\n"
        "  <link rel=\"stylesheet\" href=\"css/style.css\">\n"
        "  <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&display=swap\" rel=\"stylesheet\">\n"
        "</head>\n<body>\n"
        "  <header class=\"blog-header\">\n"
        "    <div class=\"container\">\n"
        "      <a href=\"index.html\" class=\"blog-logo\">Tech<span>Bits</span></a>\n"
        "      <nav class=\"blog-nav\">\n"
        "        <a href=\"index.html\">Stories</a>\n"
        "        <a href=\"about.html\" class=\"active\">Author</a>\n"
        "      </nav>\n"
        "    </div>\n"
        "  </header>\n"
        "  <main class=\"container main-content\">\n"
        "    <section class=\"about-section\">\n"
        "      <h1>Alexander Green</h1>\n"
        "      <p>I am a systems architect and web enthusiast who loves analyzing networking protocols, browser performance, and compiler technology.</p>\n"
        "      <p>This blog serves as my notebook where I document interesting discoveries, performance benchmarks, and thoughts on the future of programming.</p>\n"
        "    </section>\n"
        "  </main>\n"
        "  <footer>\n"
        "    <p>&copy; 2026 TechBits. Built with absolute focus.</p>\n"
        "  </footer>\n"
        "</body>\n</html>\n",
        encoding="utf-8"
    )

    # post-1.html
    (site_dir / "post-1.html").write_text(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "  <title>WebAssembly in Cloud Native Stack | TechBits</title>\n"
        "  <link rel=\"stylesheet\" href=\"css/style.css\">\n"
        "  <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&family=JetBrains+Mono&display=swap\" rel=\"stylesheet\">\n"
        "</head>\n<body>\n"
        "  <header class=\"blog-header\">\n"
        "    <div class=\"container\">\n"
        "      <a href=\"index.html\" class=\"blog-logo\">Tech<span>Bits</span></a>\n"
        "      <nav class=\"blog-nav\">\n"
        "        <a href=\"index.html\">Stories</a>\n"
        "        <a href=\"about.html\">Author</a>\n"
        "      </nav>\n"
        "    </div>\n"
        "  </header>\n"
        "  <main class=\"container main-content article-container\">\n"
        "    <article class=\"full-post\">\n"
        "      <div class=\"meta\">July 8, 2026 &bull; Systems</div>\n"
        "      <h1>The Evolution of WebAssembly in the Cloud Native Stack</h1>\n"
        "      <p>WebAssembly (Wasm) is no longer confined to the browser. As microservices look for ways to cut startup latency and decrease memory consumption, Wasm provides an attractive runtime. It compiles fast, isolates memory fully, and loads in milliseconds.</p>\n"
        "      <p>In this post, we explore how platforms like Spin and tools like Wasmtime are changing the architecture of cloud native apps.</p>\n"
        "      <pre><code>// Example Wasm component logic in Rust\n#[plugin_fn]\npub fn hello(input: String) -> FnResult&lt;String&gt; {\n    Ok(format!(\"Hello, Cloud Native! Output: {}\", input))\n}</code></pre>\n"
        "    </article>\n"
        "  </main>\n"
        "  <footer>\n"
        "    <p>&copy; 2026 TechBits. Built with absolute focus.</p>\n"
        "  </footer>\n"
        "</body>\n</html>\n",
        encoding="utf-8"
    )

    # post-2.html
    (site_dir / "post-2.html").write_text(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "  <title>Refining Micro-interactions | TechBits</title>\n"
        "  <link rel=\"stylesheet\" href=\"css/style.css\">\n"
        "  <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&display=swap\" rel=\"stylesheet\">\n"
        "</head>\n<body>\n"
        "  <header class=\"blog-header\">\n"
        "    <div class=\"container\">\n"
        "      <a href=\"index.html\" class=\"blog-logo\">Tech<span>Bits</span></a>\n"
        "      <nav class=\"blog-nav\">\n"
        "        <a href=\"index.html\">Stories</a>\n"
        "        <a href=\"about.html\">Author</a>\n"
        "      </nav>\n"
        "    </div>\n"
        "  </header>\n"
        "  <main class=\"container main-content article-container\">\n"
        "    <article class=\"full-post\">\n"
        "      <div class=\"meta\">July 2, 2026 &bull; UI/UX</div>\n"
        "      <h1>Refining Micro-interactions in Clean Design Systems</h1>\n"
        "      <p>Good interface design is about context and response. A button shouldn't just change state; it should morph smoothly. Subtle spring physics on hovers indicate responsiveness without causing clutter.</p>\n"
        "      <p>We detail CSS transitions and JS requestAnimationFrame examples that keep frame rates locked at 60fps or higher.</p>\n"
        "    </article>\n"
        "  </main>\n"
        "  <footer>\n"
        "    <p>&copy; 2026 TechBits. Built with absolute focus.</p>\n"
        "  </footer>\n"
        "</body>\n</html>\n",
        encoding="utf-8"
    )

    # style.css
    (site_dir / "css" / "style.css").write_text(
        "body {\n"
        "  margin: 0;\n"
        "  font-family: 'Outfit', sans-serif;\n"
        "  color: #1a1a1a;\n"
        "  background: #fafaf9;\n"
        "  line-height: 1.7;\n"
        "}\n"
        ".container {\n"
        "  width: 90%;\n"
        "  max-width: 900px;\n"
        "  margin: 0 auto;\n"
        "}\n"
        ".blog-header {\n"
        "  padding: 2rem 0;\n"
        "  background: #fff;\n"
        "  border-bottom: 1px solid #e7e5e4;\n"
        "}\n"
        ".blog-header .container {\n"
        "  display: flex;\n"
        "  justify-content: space-between;\n"
        "  align-items: center;\n"
        "}\n"
        ".blog-logo {\n"
        "  font-size: 1.75rem;\n"
        "  font-weight: 800;\n"
        "  color: #111;\n"
        "  text-decoration: none;\n"
        "  letter-spacing: -0.5px;\n"
        "}\n"
        ".blog-logo span {\n"
        "  color: #e11d48;\n"
        "}\n"
        ".blog-nav a {\n"
        "  margin-left: 1.5rem;\n"
        "  text-decoration: none;\n"
        "  color: #78716c;\n"
        "  font-weight: 600;\n"
        "  transition: color 0.15s;\n"
        "}\n"
        ".blog-nav a:hover, .blog-nav a.active {\n"
        "  color: #e11d48;\n"
        "}\n"
        ".main-content {\n"
        "  padding: 4rem 0;\n"
        "}\n"
        ".hero-post {\n"
        "  background: #fff;\n"
        "  border: 1px solid #e7e5e4;\n"
        "  border-radius: 12px;\n"
        "  padding: 3rem;\n"
        "  margin-bottom: 4rem;\n"
        "  box-shadow: 0 4px 12px rgba(0,0,0,0.01);\n"
        "}\n"
        ".hero-post h2 {\n"
        "  font-size: 2.25rem;\n"
        "  margin: 0.5rem 0 1.5rem 0;\n"
        "  font-weight: 800;\n"
        "  line-height: 1.3;\n"
        "}\n"
        ".hero-post h2 a {\n"
        "  color: inherit;\n"
        "  text-decoration: none;\n"
        "}\n"
        ".hero-post h2 a:hover {\n"
        "  color: #e11d48;\n"
        "}\n"
        ".meta {\n"
        "  text-transform: uppercase;\n"
        "  font-size: 0.8rem;\n"
        "  color: #a8a29e;\n"
        "  font-weight: 600;\n"
        "  letter-spacing: 1px;\n"
        "}\n"
        ".hero-post p {\n"
        "  font-size: 1.15rem;\n"
        "  color: #57534e;\n"
        "  margin: 0;\n"
        "}\n"
        ".recent-posts h3 {\n"
        "  font-size: 1.5rem;\n"
        "  font-weight: 800;\n"
        "  margin-bottom: 2rem;\n"
        "}\n"
        ".post-list {\n"
        "  display: grid;\n"
        "  grid-template-columns: 1fr;\n"
        "  gap: 2rem;\n"
        "}\n"
        ".post-item {\n"
        "  background: #fff;\n"
        "  border: 1px solid #e7e5e4;\n"
        "  padding: 2rem;\n"
        "  border-radius: 8px;\n"
        "}\n"
        ".post-item h4 {\n"
        "  font-size: 1.35rem;\n"
        "  margin: 0.5rem 0 1rem 0;\n"
        "}\n"
        ".post-item h4 a {\n"
        "  color: inherit;\n"
        "  text-decoration: none;\n"
        "}\n"
        ".post-item h4 a:hover {\n"
        "  color: #e11d48;\n"
        "}\n"
        "footer {\n"
        "  background: #1c1917;\n"
        "  color: #a8a29e;\n"
        "  text-align: center;\n"
        "  padding: 3rem 0;\n"
        "  margin-top: 6rem;\n"
        "}\n"
        ".article-container {\n"
        "  max-width: 750px;\n"
        "}\n"
        ".full-post h1 {\n"
        "  font-size: 2.5rem;\n"
        "  line-height: 1.25;\n"
        "  margin: 0.5rem 0 2rem 0;\n"
        "}\n"
        "pre {\n"
        "  background: #1c1917;\n"
        "  color: #f5f5f4;\n"
        "  padding: 1.5rem;\n"
        "  border-radius: 8px;\n"
        "  overflow-x: auto;\n"
        "  font-family: 'JetBrains Mono', monospace;\n"
        "  font-size: 0.9rem;\n"
        "}\n",
        encoding="utf-8"
    )


def _generate_docs(site_dir: Path) -> None:
    # index.html
    (site_dir / "index.html").write_text(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "  <title>HydraDB Docs | Ultimate Time-Series Storage</title>\n"
        "  <link rel=\"stylesheet\" href=\"css/style.css\">\n"
        "  <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono&display=swap\" rel=\"stylesheet\">\n"
        "</head>\n<body>\n"
        "  <div class=\"docs-layout\">\n"
        "    <aside class=\"sidebar\">\n"
        "      <div class=\"logo-area\">\n"
        "        <a href=\"index.html\" class=\"brand\">HydraDB</a>\n"
        "      </div>\n"
        "      <nav class=\"docs-nav\">\n"
        "        <span class=\"nav-title\">Introduction</span>\n"
        "        <a href=\"index.html\" class=\"active\">What is HydraDB?</a>\n"
        "        <a href=\"getting-started.html\">Getting Started</a>\n"
        "        <span class=\"nav-title\">Reference</span>\n"
        "        <a href=\"api-reference.html\">API Reference</a>\n"
        "      </nav>\n"
        "    </aside>\n"
        "    <main class=\"docs-main\">\n"
        "      <article class=\"docs-article\">\n"
        "        <h1>What is HydraDB?</h1>\n"
        "        <p>HydraDB is an open-source, distributed, transactional time-series database designed for high throughput writes and sub-millisecond query evaluation on billions of rows.</p>\n"
        "        <p>It combines the architectural elegance of log-structured merge trees with modern vector processing engines to maximize hardware utilization.</p>\n"
        "        <h2>Key Features</h2>\n"
        "        <ul>\n"
        "          <li><strong>Distributed Scaling:</strong> Multi-leader replication built on Raft consensus.</li>\n"
        "          <li><strong>High Compressibility:</strong> Dynamic delta-of-delta and Gorilla encoding.</li>\n"
        "          <li><strong>SQL Compatible:</strong> Native query compilation to machine code.</li>\n"
        "        </ul>\n"
        "      </article>\n"
        "    </main>\n"
        "  </div>\n"
        "</body>\n</html>\n",
        encoding="utf-8"
    )

    # getting-started.html
    (site_dir / "getting-started.html").write_text(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "  <title>Getting Started | HydraDB Docs</title>\n"
        "  <link rel=\"stylesheet\" href=\"css/style.css\">\n"
        "  <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono&display=swap\" rel=\"stylesheet\">\n"
        "</head>\n<body>\n"
        "  <div class=\"docs-layout\">\n"
        "    <aside class=\"sidebar\">\n"
        "      <div class=\"logo-area\">\n"
        "        <a href=\"index.html\" class=\"brand\">HydraDB</a>\n"
        "      </div>\n"
        "      <nav class=\"docs-nav\">\n"
        "        <span class=\"nav-title\">Introduction</span>\n"
        "        <a href=\"index.html\">What is HydraDB?</a>\n"
        "        <a href=\"getting-started.html\" class=\"active\">Getting Started</a>\n"
        "        <span class=\"nav-title\">Reference</span>\n"
        "        <a href=\"api-reference.html\">API Reference</a>\n"
        "      </nav>\n"
        "    </aside>\n"
        "    <main class=\"docs-main\">\n"
        "      <article class=\"docs-article\">\n"
        "        <h1>Getting Started</h1>\n"
        "        <p>Install HydraDB via our official package manager scripts or directly from source code.</p>\n"
        "        <h2>Quick Start (CLI)</h2>\n"
        "        <p>Run the following command to download and bootstrap a single-node cluster locally:</p>\n"
        "        <pre><code>curl -fsSL https://get.hydradb.org | sh\nhydradb-server start --config /etc/hydradb.conf</code></pre>\n"
        "        <h2>Running in Docker</h2>\n"
        "        <p>Alternatively, spin up a node using Docker Compose:</p>\n"
        "        <pre><code>docker run -d -p 8086:8086 hydradb/hydradb-server:latest</code></pre>\n"
        "      </article>\n"
        "    </main>\n"
        "  </div>\n"
        "</body>\n</html>\n",
        encoding="utf-8"
    )

    # api-reference.html
    (site_dir / "api-reference.html").write_text(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "  <title>API Reference | HydraDB Docs</title>\n"
        "  <link rel=\"stylesheet\" href=\"css/style.css\">\n"
        "  <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono&display=swap\" rel=\"stylesheet\">\n"
        "</head>\n<body>\n"
        "  <div class=\"docs-layout\">\n"
        "    <aside class=\"sidebar\">\n"
        "      <div class=\"logo-area\">\n"
        "        <a href=\"index.html\" class=\"brand\">HydraDB</a>\n"
        "      </div>\n"
        "      <nav class=\"docs-nav\">\n"
        "        <span class=\"nav-title\">Introduction</span>\n"
        "        <a href=\"index.html\">What is HydraDB?</a>\n"
        "        <a href=\"getting-started.html\">Getting Started</a>\n"
        "        <span class=\"nav-title\">Reference</span>\n"
        "        <a href=\"api-reference.html\" class=\"active\">API Reference</a>\n"
        "      </nav>\n"
        "    </aside>\n"
        "    <main class=\"docs-main\">\n"
        "      <article class=\"docs-article\">\n"
        "        <h1>API Reference</h1>\n"
        "        <p>The HydraDB API exposes standard HTTP endpoints to write metrics, manage tables, and execute query expressions.</p>\n"
        "        <h2>Write Metrics</h2>\n"
        "        <p>Endpoint: <code>POST /api/v1/write</code></p>\n"
        "        <pre><code>curl -i -XPOST \"http://localhost:8086/api/v1/write?db=metrics\" \\\n  --data-binary \"cpu_usage,host=server01 value=0.64\"</code></pre>\n"
        "      </article>\n"
        "    </main>\n"
        "  </div>\n"
        "</body>\n</html>\n",
        encoding="utf-8"
    )

    # style.css
    (site_dir / "css" / "style.css").write_text(
        "body {\n"
        "  margin: 0;\n"
        "  font-family: 'Inter', sans-serif;\n"
        "  color: #334155;\n"
        "  background: #ffffff;\n"
        "  line-height: 1.6;\n"
        "}\n"
        ".docs-layout {\n"
        "  display: flex;\n"
        "  min-height: 100vh;\n"
        "}\n"
        ".sidebar {\n"
        "  width: 280px;\n"
        "  background: #f8fafc;\n"
        "  border-right: 1px solid #e2e8f0;\n"
        "  padding: 2rem;\n"
        "  flex-shrink: 0;\n"
        "}\n"
        ".brand {\n"
        "  font-size: 1.5rem;\n"
        "  font-weight: 700;\n"
        "  color: #0f172a;\n"
        "  text-decoration: none;\n"
        "}\n"
        ".logo-area {\n"
        "  margin-bottom: 2.5rem;\n"
        "}\n"
        ".docs-nav {\n"
        "  display: flex;\n"
        "  flex-direction: column;\n"
        "}\n"
        ".nav-title {\n"
        "  font-size: 0.75rem;\n"
        "  text-transform: uppercase;\n"
        "  font-weight: 700;\n"
        "  color: #94a3b8;\n"
        "  margin: 1.5rem 0 0.5rem 0;\n"
        "  letter-spacing: 0.5px;\n"
        "}\n"
        ".docs-nav a {\n"
        "  text-decoration: none;\n"
        "  color: #475569;\n"
        "  padding: 0.4rem 0;\n"
        "  font-size: 0.95rem;\n"
        "  font-weight: 500;\n"
        "  transition: color 0.15s;\n"
        "}\n"
        ".docs-nav a:hover, .docs-nav a.active {\n"
        "  color: #0f172a;\n"
        "  font-weight: 600;\n"
        "}\n"
        ".docs-main {\n"
        "  flex-grow: 1;\n"
        "  padding: 4rem 5rem;\n"
        "  max-width: 800px;\n"
        "}\n"
        ".docs-article h1 {\n"
        "  font-size: 2.5rem;\n"
        "  font-weight: 800;\n"
        "  color: #0f172a;\n"
        "  margin: 0 0 1.5rem 0;\n"
        "}\n"
        ".docs-article h2 {\n"
        "  font-size: 1.5rem;\n"
        "  font-weight: 700;\n"
        "  color: #1e293b;\n"
        "  margin: 2.5rem 0 1rem 0;\n"
        "}\n"
        "code {\n"
        "  font-family: 'JetBrains Mono', monospace;\n"
        "  background: #f1f5f9;\n"
        "  color: #0f172a;\n"
        "  padding: 0.2rem 0.4rem;\n"
        "  border-radius: 4px;\n"
        "  font-size: 0.875rem;\n"
        "}\n"
        "pre {\n"
        "  background: #0f172a;\n"
        "  color: #f8fafc;\n"
        "  padding: 1.5rem;\n"
        "  border-radius: 8px;\n"
        "  overflow-x: auto;\n"
        "  margin: 1.5rem 0;\n"
        "}\n"
        "pre code {\n"
        "  background: transparent;\n"
        "  color: inherit;\n"
        "  padding: 0;\n"
        "}\n"
        "strong {\n"
        "  color: #0f172a;\n"
        "}\n",
        encoding="utf-8"
    )
