"""Key material generated by the Sing-Box binary."""
from __future__ import annotations


def generate_reality_keypair() -> tuple[str, str]:
    """Return a fresh Reality (private, public) X25519 pair from the kernel."""
    from hydra.core.singbox import _find_singbox, _run

    binary = _find_singbox()
    if not binary:
        raise RuntimeError(
            "sing-box не установлен: невозможно создать ключи Reality",
        )
    result = _run([str(binary), "generate", "reality-keypair"])
    if result.returncode != 0:
        raise RuntimeError("sing-box не смог создать пару ключей Reality")
    keys: dict[str, str] = {}
    for line in str(result.stdout or "").splitlines():
        name, separator, value = line.partition(":")
        if separator:
            keys[name.strip().lower()] = value.strip()
    private_key = keys.get("privatekey", "")
    public_key = keys.get("publickey", "")
    if not private_key or not public_key:
        raise RuntimeError("вывод sing-box не содержит пары ключей Reality")
    return private_key, public_key


__all__ = ["generate_reality_keypair"]
