"""Blog-theme decoy site renderer."""
from __future__ import annotations

from pathlib import Path


def generate(site_dir: Path) -> None:
    """Render every file in the blog theme."""
    _write_index(site_dir)
    _write_about(site_dir)
    _write_post_one(site_dir)
    _write_post_two(site_dir)
    _write_styles(site_dir)


def _write_index(site_dir: Path) -> None:
    (site_dir / "index.html").write_text(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "  <title>TechBits | Insights on Modern Software</title>\n"
        "  <link rel=\"stylesheet\" href=\"css/style.css\">\n"
        "  <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&family=JetBrains+Mono&display=swap\" rel=\"stylesheet\">\n"
        "</head>\n<body>\n"
        "  <header class=\"blog-header\">\n"
        "    <div class=\"container\">\n"
        "      <a href=\"index.html\" class=\"blog-logo\">Tech<span>Bits</span></a>\n"
        "      <nav class=\"blog-nav\">\n"
        "        <a href=\"index.html\" class=\"active\">Stories</a>\n"
        "        <a href=\"about.html\">Author</a>\n"
        "      </nav>\n"
        "    </div>\n"
        "  </header>\n"
        "  <main class=\"container main-content\">\n"
        "    <section class=\"hero-post\">\n"
        "      <div class=\"meta\">Featured &bull; July 2026</div>\n"
        "      <h2><a href=\"post-1.html\">The Evolution of WebAssembly in the Cloud Native Stack</a></h2>\n"
        "      <p>How WebAssembly (Wasm) is evolving from a browser optimization tool into a lightweight, fast, and secure alternative for containerized workloads in production environments.</p>\n"
        "    </section>\n"
        "    <section class=\"recent-posts\">\n"
        "      <h3>Recent Articles</h3>\n"
        "      <div class=\"post-list\">\n"
        "        <article class=\"post-item\">\n"
        "          <div class=\"meta\">Design &bull; July 2, 2026</div>\n"
        "          <h4><a href=\"post-2.html\">Refining Micro-interactions in Clean Design Systems</a></h4>\n"
        "          <p>A deep dive into how subtle animations can delight users and drastically improve conversion and accessibility.</p>\n"
        "        </article>\n"
        "      </div>\n"
        "    </section>\n"
        "  </main>\n"
        "  <footer>\n"
        "    <p>&copy; 2026 TechBits. Built with absolute focus.</p>\n"
        "  </footer>\n"
        "</body>\n</html>\n",
        encoding="utf-8"
    )



def _write_about(site_dir: Path) -> None:
    (site_dir / "about.html").write_text(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "  <title>About the Author | TechBits</title>\n"
        "  <link rel=\"stylesheet\" href=\"css/style.css\">\n"
        "  <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&display=swap\" rel=\"stylesheet\">\n"
        "</head>\n<body>\n"
        "  <header class=\"blog-header\">\n"
        "    <div class=\"container\">\n"
        "      <a href=\"index.html\" class=\"blog-logo\">Tech<span>Bits</span></a>\n"
        "      <nav class=\"blog-nav\">\n"
        "        <a href=\"index.html\">Stories</a>\n"
        "        <a href=\"about.html\" class=\"active\">Author</a>\n"
        "      </nav>\n"
        "    </div>\n"
        "  </header>\n"
        "  <main class=\"container main-content\">\n"
        "    <section class=\"about-section\">\n"
        "      <h1>Alexander Green</h1>\n"
        "      <p>I am a systems architect and web enthusiast who loves analyzing networking protocols, browser performance, and compiler technology.</p>\n"
        "      <p>This blog serves as my notebook where I document interesting discoveries, performance benchmarks, and thoughts on the future of programming.</p>\n"
        "    </section>\n"
        "  </main>\n"
        "  <footer>\n"
        "    <p>&copy; 2026 TechBits. Built with absolute focus.</p>\n"
        "  </footer>\n"
        "</body>\n</html>\n",
        encoding="utf-8"
    )



def _write_post_one(site_dir: Path) -> None:
    (site_dir / "post-1.html").write_text(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "  <title>WebAssembly in Cloud Native Stack | TechBits</title>\n"
        "  <link rel=\"stylesheet\" href=\"css/style.css\">\n"
        "  <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&family=JetBrains+Mono&display=swap\" rel=\"stylesheet\">\n"
        "</head>\n<body>\n"
        "  <header class=\"blog-header\">\n"
        "    <div class=\"container\">\n"
        "      <a href=\"index.html\" class=\"blog-logo\">Tech<span>Bits</span></a>\n"
        "      <nav class=\"blog-nav\">\n"
        "        <a href=\"index.html\">Stories</a>\n"
        "        <a href=\"about.html\">Author</a>\n"
        "      </nav>\n"
        "    </div>\n"
        "  </header>\n"
        "  <main class=\"container main-content article-container\">\n"
        "    <article class=\"full-post\">\n"
        "      <div class=\"meta\">July 8, 2026 &bull; Systems</div>\n"
        "      <h1>The Evolution of WebAssembly in the Cloud Native Stack</h1>\n"
        "      <p>WebAssembly (Wasm) is no longer confined to the browser. As microservices look for ways to cut startup latency and decrease memory consumption, Wasm provides an attractive runtime. It compiles fast, isolates memory fully, and loads in milliseconds.</p>\n"
        "      <p>In this post, we explore how platforms like Spin and tools like Wasmtime are changing the architecture of cloud native apps.</p>\n"
        "      <pre><code>// Example Wasm component logic in Rust\n#[plugin_fn]\npub fn hello(input: String) -> FnResult&lt;String&gt; {\n    Ok(format!(\"Hello, Cloud Native! Output: {}\", input))\n}</code></pre>\n"
        "    </article>\n"
        "  </main>\n"
        "  <footer>\n"
        "    <p>&copy; 2026 TechBits. Built with absolute focus.</p>\n"
        "  </footer>\n"
        "</body>\n</html>\n",
        encoding="utf-8"
    )



def _write_post_two(site_dir: Path) -> None:
    (site_dir / "post-2.html").write_text(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "  <title>Refining Micro-interactions | TechBits</title>\n"
        "  <link rel=\"stylesheet\" href=\"css/style.css\">\n"
        "  <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&display=swap\" rel=\"stylesheet\">\n"
        "</head>\n<body>\n"
        "  <header class=\"blog-header\">\n"
        "    <div class=\"container\">\n"
        "      <a href=\"index.html\" class=\"blog-logo\">Tech<span>Bits</span></a>\n"
        "      <nav class=\"blog-nav\">\n"
        "        <a href=\"index.html\">Stories</a>\n"
        "        <a href=\"about.html\">Author</a>\n"
        "      </nav>\n"
        "    </div>\n"
        "  </header>\n"
        "  <main class=\"container main-content article-container\">\n"
        "    <article class=\"full-post\">\n"
        "      <div class=\"meta\">July 2, 2026 &bull; UI/UX</div>\n"
        "      <h1>Refining Micro-interactions in Clean Design Systems</h1>\n"
        "      <p>Good interface design is about context and response. A button shouldn't just change state; it should morph smoothly. Subtle spring physics on hovers indicate responsiveness without causing clutter.</p>\n"
        "      <p>We detail CSS transitions and JS requestAnimationFrame examples that keep frame rates locked at 60fps or higher.</p>\n"
        "    </article>\n"
        "  </main>\n"
        "  <footer>\n"
        "    <p>&copy; 2026 TechBits. Built with absolute focus.</p>\n"
        "  </footer>\n"
        "</body>\n</html>\n",
        encoding="utf-8"
    )



def _write_styles(site_dir: Path) -> None:
    (site_dir / "css" / "style.css").write_text(_STYLES, encoding="utf-8")


_STYLES = (
        "body {\n"
        "  margin: 0;\n"
        "  font-family: 'Outfit', sans-serif;\n"
        "  color: #1a1a1a;\n"
        "  background: #fafaf9;\n"
        "  line-height: 1.7;\n"
        "}\n"
        ".container {\n"
        "  width: 90%;\n"
        "  max-width: 900px;\n"
        "  margin: 0 auto;\n"
        "}\n"
        ".blog-header {\n"
        "  padding: 2rem 0;\n"
        "  background: #fff;\n"
        "  border-bottom: 1px solid #e7e5e4;\n"
        "}\n"
        ".blog-header .container {\n"
        "  display: flex;\n"
        "  justify-content: space-between;\n"
        "  align-items: center;\n"
        "}\n"
        ".blog-logo {\n"
        "  font-size: 1.75rem;\n"
        "  font-weight: 800;\n"
        "  color: #111;\n"
        "  text-decoration: none;\n"
        "  letter-spacing: -0.5px;\n"
        "}\n"
        ".blog-logo span {\n"
        "  color: #e11d48;\n"
        "}\n"
        ".blog-nav a {\n"
        "  margin-left: 1.5rem;\n"
        "  text-decoration: none;\n"
        "  color: #78716c;\n"
        "  font-weight: 600;\n"
        "  transition: color 0.15s;\n"
        "}\n"
        ".blog-nav a:hover, .blog-nav a.active {\n"
        "  color: #e11d48;\n"
        "}\n"
        ".main-content {\n"
        "  padding: 4rem 0;\n"
        "}\n"
        ".hero-post {\n"
        "  background: #fff;\n"
        "  border: 1px solid #e7e5e4;\n"
        "  border-radius: 12px;\n"
        "  padding: 3rem;\n"
        "  margin-bottom: 4rem;\n"
        "  box-shadow: 0 4px 12px rgba(0,0,0,0.01);\n"
        "}\n"
        ".hero-post h2 {\n"
        "  font-size: 2.25rem;\n"
        "  margin: 0.5rem 0 1.5rem 0;\n"
        "  font-weight: 800;\n"
        "  line-height: 1.3;\n"
        "}\n"
        ".hero-post h2 a {\n"
        "  color: inherit;\n"
        "  text-decoration: none;\n"
        "}\n"
        ".hero-post h2 a:hover {\n"
        "  color: #e11d48;\n"
        "}\n"
        ".meta {\n"
        "  text-transform: uppercase;\n"
        "  font-size: 0.8rem;\n"
        "  color: #a8a29e;\n"
        "  font-weight: 600;\n"
        "  letter-spacing: 1px;\n"
        "}\n"
        ".hero-post p {\n"
        "  font-size: 1.15rem;\n"
        "  color: #57534e;\n"
        "  margin: 0;\n"
        "}\n"
        ".recent-posts h3 {\n"
        "  font-size: 1.5rem;\n"
        "  font-weight: 800;\n"
        "  margin-bottom: 2rem;\n"
        "}\n"
        ".post-list {\n"
        "  display: grid;\n"
        "  grid-template-columns: 1fr;\n"
        "  gap: 2rem;\n"
        "}\n"
        ".post-item {\n"
        "  background: #fff;\n"
        "  border: 1px solid #e7e5e4;\n"
        "  padding: 2rem;\n"
        "  border-radius: 8px;\n"
        "}\n"
        ".post-item h4 {\n"
        "  font-size: 1.35rem;\n"
        "  margin: 0.5rem 0 1rem 0;\n"
        "}\n"
        ".post-item h4 a {\n"
        "  color: inherit;\n"
        "  text-decoration: none;\n"
        "}\n"
        ".post-item h4 a:hover {\n"
        "  color: #e11d48;\n"
        "}\n"
        "footer {\n"
        "  background: #1c1917;\n"
        "  color: #a8a29e;\n"
        "  text-align: center;\n"
        "  padding: 3rem 0;\n"
        "  margin-top: 6rem;\n"
        "}\n"
        ".article-container {\n"
        "  max-width: 750px;\n"
        "}\n"
        ".full-post h1 {\n"
        "  font-size: 2.5rem;\n"
        "  line-height: 1.25;\n"
        "  margin: 0.5rem 0 2rem 0;\n"
        "}\n"
        "pre {\n"
        "  background: #1c1917;\n"
        "  color: #f5f5f4;\n"
        "  padding: 1.5rem;\n"
        "  border-radius: 8px;\n"
        "  overflow-x: auto;\n"
        "  font-family: 'JetBrains Mono', monospace;\n"
        "  font-size: 0.9rem;\n"
        "}\n"
)
