"""Documentation-theme decoy site renderer."""
from __future__ import annotations

from pathlib import Path


def generate(site_dir: Path) -> None:
    """Render every file in the documentation theme."""
    _write_index(site_dir)
    _write_getting_started(site_dir)
    _write_api_reference(site_dir)
    _write_styles(site_dir)


def _write_index(site_dir: Path) -> None:
    (site_dir / "index.html").write_text(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "  <title>HydraDB Docs | Ultimate Time-Series Storage</title>\n"
        "  <link rel=\"stylesheet\" href=\"css/style.css\">\n"
        "  <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono&display=swap\" rel=\"stylesheet\">\n"
        "</head>\n<body>\n"
        "  <div class=\"docs-layout\">\n"
        "    <aside class=\"sidebar\">\n"
        "      <div class=\"logo-area\">\n"
        "        <a href=\"index.html\" class=\"brand\">HydraDB</a>\n"
        "      </div>\n"
        "      <nav class=\"docs-nav\">\n"
        "        <span class=\"nav-title\">Introduction</span>\n"
        "        <a href=\"index.html\" class=\"active\">What is HydraDB?</a>\n"
        "        <a href=\"getting-started.html\">Getting Started</a>\n"
        "        <span class=\"nav-title\">Reference</span>\n"
        "        <a href=\"api-reference.html\">API Reference</a>\n"
        "      </nav>\n"
        "    </aside>\n"
        "    <main class=\"docs-main\">\n"
        "      <article class=\"docs-article\">\n"
        "        <h1>What is HydraDB?</h1>\n"
        "        <p>HydraDB is an open-source, distributed, transactional time-series database designed for high throughput writes and sub-millisecond query evaluation on billions of rows.</p>\n"
        "        <p>It combines the architectural elegance of log-structured merge trees with modern vector processing engines to maximize hardware utilization.</p>\n"
        "        <h2>Key Features</h2>\n"
        "        <ul>\n"
        "          <li><strong>Distributed Scaling:</strong> Multi-leader replication built on Raft consensus.</li>\n"
        "          <li><strong>High Compressibility:</strong> Dynamic delta-of-delta and Gorilla encoding.</li>\n"
        "          <li><strong>SQL Compatible:</strong> Native query compilation to machine code.</li>\n"
        "        </ul>\n"
        "      </article>\n"
        "    </main>\n"
        "  </div>\n"
        "</body>\n</html>\n",
        encoding="utf-8"
    )



def _write_getting_started(site_dir: Path) -> None:
    (site_dir / "getting-started.html").write_text(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "  <title>Getting Started | HydraDB Docs</title>\n"
        "  <link rel=\"stylesheet\" href=\"css/style.css\">\n"
        "  <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono&display=swap\" rel=\"stylesheet\">\n"
        "</head>\n<body>\n"
        "  <div class=\"docs-layout\">\n"
        "    <aside class=\"sidebar\">\n"
        "      <div class=\"logo-area\">\n"
        "        <a href=\"index.html\" class=\"brand\">HydraDB</a>\n"
        "      </div>\n"
        "      <nav class=\"docs-nav\">\n"
        "        <span class=\"nav-title\">Introduction</span>\n"
        "        <a href=\"index.html\">What is HydraDB?</a>\n"
        "        <a href=\"getting-started.html\" class=\"active\">Getting Started</a>\n"
        "        <span class=\"nav-title\">Reference</span>\n"
        "        <a href=\"api-reference.html\">API Reference</a>\n"
        "      </nav>\n"
        "    </aside>\n"
        "    <main class=\"docs-main\">\n"
        "      <article class=\"docs-article\">\n"
        "        <h1>Getting Started</h1>\n"
        "        <p>Install HydraDB via our official package manager scripts or directly from source code.</p>\n"
        "        <h2>Quick Start (CLI)</h2>\n"
        "        <p>Run the following command to download and bootstrap a single-node cluster locally:</p>\n"
        "        <pre><code>curl -fsSL https://get.hydradb.org | sh\nhydradb-server start --config /etc/hydradb.conf</code></pre>\n"
        "        <h2>Running in Docker</h2>\n"
        "        <p>Alternatively, spin up a node using Docker Compose:</p>\n"
        "        <pre><code>docker run -d -p 8086:8086 hydradb/hydradb-server:latest</code></pre>\n"
        "      </article>\n"
        "    </main>\n"
        "  </div>\n"
        "</body>\n</html>\n",
        encoding="utf-8"
    )



def _write_api_reference(site_dir: Path) -> None:
    (site_dir / "api-reference.html").write_text(
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
        "  <meta charset=\"UTF-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "  <title>API Reference | HydraDB Docs</title>\n"
        "  <link rel=\"stylesheet\" href=\"css/style.css\">\n"
        "  <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono&display=swap\" rel=\"stylesheet\">\n"
        "</head>\n<body>\n"
        "  <div class=\"docs-layout\">\n"
        "    <aside class=\"sidebar\">\n"
        "      <div class=\"logo-area\">\n"
        "        <a href=\"index.html\" class=\"brand\">HydraDB</a>\n"
        "      </div>\n"
        "      <nav class=\"docs-nav\">\n"
        "        <span class=\"nav-title\">Introduction</span>\n"
        "        <a href=\"index.html\">What is HydraDB?</a>\n"
        "        <a href=\"getting-started.html\">Getting Started</a>\n"
        "        <span class=\"nav-title\">Reference</span>\n"
        "        <a href=\"api-reference.html\" class=\"active\">API Reference</a>\n"
        "      </nav>\n"
        "    </aside>\n"
        "    <main class=\"docs-main\">\n"
        "      <article class=\"docs-article\">\n"
        "        <h1>API Reference</h1>\n"
        "        <p>The HydraDB API exposes standard HTTP endpoints to write metrics, manage tables, and execute query expressions.</p>\n"
        "        <h2>Write Metrics</h2>\n"
        "        <p>Endpoint: <code>POST /api/v1/write</code></p>\n"
        "        <pre><code>curl -i -XPOST \"http://localhost:8086/api/v1/write?db=metrics\" \\\n  --data-binary \"cpu_usage,host=server01 value=0.64\"</code></pre>\n"
        "      </article>\n"
        "    </main>\n"
        "  </div>\n"
        "</body>\n</html>\n",
        encoding="utf-8"
    )



def _write_styles(site_dir: Path) -> None:
    (site_dir / "css" / "style.css").write_text(
        "body {\n"
        "  margin: 0;\n"
        "  font-family: 'Inter', sans-serif;\n"
        "  color: #334155;\n"
        "  background: #ffffff;\n"
        "  line-height: 1.6;\n"
        "}\n"
        ".docs-layout {\n"
        "  display: flex;\n"
        "  min-height: 100vh;\n"
        "}\n"
        ".sidebar {\n"
        "  width: 280px;\n"
        "  background: #f8fafc;\n"
        "  border-right: 1px solid #e2e8f0;\n"
        "  padding: 2rem;\n"
        "  flex-shrink: 0;\n"
        "}\n"
        ".brand {\n"
        "  font-size: 1.5rem;\n"
        "  font-weight: 700;\n"
        "  color: #0f172a;\n"
        "  text-decoration: none;\n"
        "}\n"
        ".logo-area {\n"
        "  margin-bottom: 2.5rem;\n"
        "}\n"
        ".docs-nav {\n"
        "  display: flex;\n"
        "  flex-direction: column;\n"
        "}\n"
        ".nav-title {\n"
        "  font-size: 0.75rem;\n"
        "  text-transform: uppercase;\n"
        "  font-weight: 700;\n"
        "  color: #94a3b8;\n"
        "  margin: 1.5rem 0 0.5rem 0;\n"
        "  letter-spacing: 0.5px;\n"
        "}\n"
        ".docs-nav a {\n"
        "  text-decoration: none;\n"
        "  color: #475569;\n"
        "  padding: 0.4rem 0;\n"
        "  font-size: 0.95rem;\n"
        "  font-weight: 500;\n"
        "  transition: color 0.15s;\n"
        "}\n"
        ".docs-nav a:hover, .docs-nav a.active {\n"
        "  color: #0f172a;\n"
        "  font-weight: 600;\n"
        "}\n"
        ".docs-main {\n"
        "  flex-grow: 1;\n"
        "  padding: 4rem 5rem;\n"
        "  max-width: 800px;\n"
        "}\n"
        ".docs-article h1 {\n"
        "  font-size: 2.5rem;\n"
        "  font-weight: 800;\n"
        "  color: #0f172a;\n"
        "  margin: 0 0 1.5rem 0;\n"
        "}\n"
        ".docs-article h2 {\n"
        "  font-size: 1.5rem;\n"
        "  font-weight: 700;\n"
        "  color: #1e293b;\n"
        "  margin: 2.5rem 0 1rem 0;\n"
        "}\n"
        "code {\n"
        "  font-family: 'JetBrains Mono', monospace;\n"
        "  background: #f1f5f9;\n"
        "  color: #0f172a;\n"
        "  padding: 0.2rem 0.4rem;\n"
        "  border-radius: 4px;\n"
        "  font-size: 0.875rem;\n"
        "}\n"
        "pre {\n"
        "  background: #0f172a;\n"
        "  color: #f8fafc;\n"
        "  padding: 1.5rem;\n"
        "  border-radius: 8px;\n"
        "  overflow-x: auto;\n"
        "  margin: 1.5rem 0;\n"
        "}\n"
        "pre code {\n"
        "  background: transparent;\n"
        "  color: inherit;\n"
        "  padding: 0;\n"
        "}\n"
        "strong {\n"
        "  color: #0f172a;\n"
        "}\n",
        encoding="utf-8"
    )
