"""WireGuard key material, generated by HYDRA instead of by a host tool.

The core serves the tunnel, so there is no `awg` binary to ask for a keypair: the same Curve25519
math the tool performs happens here, and the stored form is the base64 WireGuard uses everywhere.
"""

from __future__ import annotations

import base64
import secrets

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey


def _b64(raw: bytes) -> str:
    return base64.b64encode(raw).decode()


def generate_private_key() -> str:
    """A clamped Curve25519 private key, in the form WireGuard hands it out."""
    raw = bytearray(secrets.token_bytes(32))
    raw[0] &= 248
    raw[31] &= 127
    raw[31] |= 64
    return _b64(bytes(raw))


def public_key(private_key: str) -> str:
    """The public key belonging to a base64 private key."""
    key = X25519PrivateKey.from_private_bytes(base64.b64decode(private_key))
    raw = key.public_key().public_bytes(
        serialization.Encoding.Raw,
        serialization.PublicFormat.Raw,
    )
    return _b64(raw)


def generate_preshared_key() -> str:
    """A pre-shared key: thirty-two random bytes, nothing derived from them."""
    return _b64(secrets.token_bytes(32))
