"""Explicit application port for privileged administration operations.

UI adapters depend on this transport-neutral contract.  The production
implementation lives in :mod:`hydra.services.admin_infrastructure`; tests can
inject a small fake without patching host globals.
"""
from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol, Sequence

from hydra.core.state_models import AppState


@dataclass(frozen=True)
class AdminCommandResult:
    ok: bool
    code: str = ""
    message: str = ""
    detail: str = ""


@dataclass(frozen=True)
class SingboxDiagnostics:
    installed: bool
    running: bool = False
    version: str = ""
    config_exists: bool = False
    config_check_ok: bool | None = None
    config_check_detail: str = ""


@dataclass(frozen=True)
class UnitDiagnostics:
    loaded: bool
    active: str = ""
    enabled: str = ""
    active_ok: bool = False
    enabled_ok: bool = False


@dataclass(frozen=True)
class SystemOverview:
    hostname: str = ""
    cpu_percent: float | None = None
    memory_used: int = 0
    memory_total: int = 0
    memory_percent: float | None = None
    disk_used: int = 0
    disk_total: int = 0
    disk_percent: float | None = None
    uptime_seconds: int | None = None
    load_averages: tuple[float, float] | None = None
    public_ip: str = ""
    local_ip: str = ""
    country_flag: str = ""
    dns: str = ""
    dnscrypt_active: bool = False
    dnscrypt_servers: tuple[str, ...] = ()


class AdminOperations(Protocol):
    """Commands and queries needed by local administration adapters."""

    def load_state(self) -> AppState: ...
    def save_state(self, state: AppState) -> None: ...
    def set_install_flag(self, key: str, value: bool) -> AppState: ...
    def set_clash_api(self, enabled: bool) -> AppState: ...

    def unit_active(self, unit: str) -> bool: ...
    def unit_known(self, unit: str) -> bool: ...
    def start_unit(self, unit: str) -> bool: ...
    def stop_unit(self, unit: str) -> bool: ...
    def restart_unit(self, unit: str) -> bool: ...
    def disable_unit(self, unit: str) -> bool: ...

    def install_subscription_service(self, state: AppState) -> bool: ...
    def subscription_certificate(self, state: AppState) -> tuple[str | None, str | None]: ...
    def subscription_public_host(self, state: AppState) -> str: ...
    def obtain_subscription_certificate(self, domain: str) -> AdminCommandResult: ...
    def update_subscription_domain(self, state: AppState, domain: str) -> AdminCommandResult: ...
    def refresh_subscription_routing(self, state: AppState) -> bool: ...

    def install_admin_bot(self, state: AppState) -> AdminCommandResult: ...
    def stop_admin_bot(self, state: AppState) -> AdminCommandResult: ...
    def configure_sync_agent(self, enabled: bool) -> bool: ...
    def run_sync_agent(self) -> tuple[bool, str]: ...

    def install_packages(self, packages: Sequence[str]) -> bool: ...
    def run_command(self, args: Sequence[object], **kwargs: Any) -> subprocess.CompletedProcess: ...
    def popen_command(self, args: Sequence[object], **kwargs: Any) -> subprocess.Popen: ...
    def singbox_diagnostics(self) -> SingboxDiagnostics: ...
    def install_singbox(self, *, force: bool = False) -> bool: ...
    def update_singbox(self) -> tuple[bool, str]: ...
    def start_singbox(self) -> bool: ...
    def stop_singbox(self) -> bool: ...
    def apply_network_tuning(self) -> dict[str, Any]: ...
    def rollback_network_tuning(self) -> dict[str, Any]: ...
    def system_overview(self, state: AppState) -> SystemOverview: ...
    def unit_diagnostics(self, unit: str) -> UnitDiagnostics: ...
    def read_text_lines(self, path: Path) -> list[str]: ...
    def read_bytes(self, path: Path) -> bytes: ...
    def atomic_write(self, path: Path, content: str | bytes) -> None: ...


class UnavailableAdminOperations:
    """Default for manually assembled applications that do not need admin I/O."""

    def __getattr__(self, name: str):
        raise RuntimeError(f"administration operation is not configured: {name}")
