"""Declarative export and monkeypatch contract for :mod:`hydra.ui.menus`."""
from __future__ import annotations

from types import ModuleType

from hydra.ui._menus import (
    client_status,
    core,
    extended_protocols,
    monitoring,
    plugin_settings,
    protocols,
    root,
    security,
    telegram,
    users,
    users_links,
    users_management,
    users_overview,
    users_subscription,
)


COMMON_TUI = (
    "clear", "confirm", "error", "info", "kv", "menu", "panel", "prompt",
    "success", "title", "warn", "BANNER", "BOLD", "CYAN", "DIM", "GREEN",
    "NC", "PANEL_W", "RED", "WHITE", "YELLOW", "_bar", "_bytes_auto", "_ok",
)
BINDER_SPECS: dict[
    str,
    tuple[ModuleType, tuple[str, ...], tuple[ModuleType, ...]],
] = {
    "_root_menus": (root, COMMON_TUI, ()),
    "_core_menus": (
        core,
        COMMON_TUI + (
            "_apply_error_text",
            "_apply_network_tuning_menu",
            "_rollback_network_tuning_menu",
        ),
        (),
    ),
    "_protocol_menus": (
        protocols,
        COMMON_TUI + (
            "_apply_error_text",
            "_show_plugin_clients",
            "menu_plugin",
            "protocol_menu_title",
            "protocol_status_panel",
            "enhancement_options",
            "enhancement_summary_lines",
            "menu_footer",
            "transport_options",
            "transport_summary_lines",
        ),
        (plugin_settings,),
    ),
    "_user_menus": (
        users,
        COMMON_TUI + (
            "_application",
            "_add_user",
            "_obtain_cert_for_sub",
            "_reconcile_user_access",
            "_select_user",
            "_show_subscription_links",
            "_show_user_detail",
            "_show_users",
            "_toggle_block",
            "_user_configs",
            "_user_detail_menu",
            "_user_links",
            "get_subscription_urls",
            "get_user_access_status",
            "get_user_entitlement_status",
            "install_sub_systemd_service",
            "menu_subscription_server",
        ),
        (
            users_links,
            users_management,
            users_overview,
            users_subscription,
        ),
    ),
    "_telegram_menus": (
        telegram,
        COMMON_TUI + ("_install_admin_bot",),
        (),
    ),
    "_monitoring_menus": (
        monitoring,
        COMMON_TUI + (
            "_application",
            "_apply_error_text",
            "_is_enter_pressed",
            "_log_source_status",
            "_menu_clash_api",
            "_menu_logs",
            "_menu_service_settings",
            "_menu_sync_agent",
            "_read_proc_mem",
            "_select_user",
            "_show_connections",
            "_show_log_file",
            "_show_log_source",
            "_show_realtime_sys_monitor",
            "_show_traffic_combined",
            "_show_user_detail",
            "_sync_agent_log_snapshot",
            "_unit_active",
            "_unit_known",
            "log_viewer",
            "system_monitor",
        ),
        (),
    ),
    "_security_menus": (
        security,
        COMMON_TUI + ("menu_plugin",),
        (),
    ),
    "_extended_protocol_menus": (
        extended_protocols,
        COMMON_TUI + (
            "_application",
            "_apply_error_text",
            "_awg_generate_wizard",
            "_awg_generate_wizard_menu",
            "_manage_awg_profiles",
            "_menu_anytls_obfuscation",
            "_menu_mieru_obfuscation",
            "_rotate_awg_obfuscation",
            "_show_plugin_clients",
            "_tune_awg_hardware",
            "protocol_menu_title",
            "protocol_status_panel",
        ),
        (client_status,),
    ),
}
FORWARD_GROUPS = {
    "_root_menus": ("_sys_info",),
    "_core_menus": (
        "_apply_network_tuning_menu",
        "_rollback_network_tuning_menu",
        "menu_core",
    ),
    "_protocol_menus": (
        "_menu_hysteria2_settings",
        "_menu_snell_settings",
        "menu_network_services",
        "menu_plugin",
        "menu_protocols",
    ),
    "_user_menus": (
        "_add_user",
        "_obtain_cert_for_sub",
        "_reconcile_user_access",
        "_select_user",
        "_show_subscription_links",
        "_show_user_detail",
        "_show_users",
        "_toggle_block",
        "_user_configs",
        "_user_detail_menu",
        "_user_links",
        "install_sub_systemd_service",
        "menu_subscription_server",
        "menu_users",
    ),
    "_telegram_menus": ("_install_admin_bot", "menu_telegram"),
    "_monitoring_menus": (
        "_is_enter_pressed",
        "_log_source_status",
        "_menu_clash_api",
        "_menu_logs",
        "_menu_service_settings",
        "_menu_sync_agent",
        "_read_log_source",
        "_read_proc_cpu",
        "_read_proc_mem",
        "_read_proc_net",
        "_show_connections",
        "_show_log_file",
        "_show_log_source",
        "_show_realtime_sys_monitor",
        "_show_status",
        "_show_traffic_combined",
        "_sync_agent_log_snapshot",
        "_unit_active",
        "_unit_known",
        "_watch_journal",
        "_watch_log_file",
        "menu_monitoring",
    ),
    "_security_menus": ("_toggle_security_plugin", "menu_security"),
    "_extended_protocol_menus": (
        "_awg_generate_wizard",
        "_awg_generate_wizard_menu",
        "_manage_awg_profiles",
        "_menu_amneziawg",
        "_menu_anytls",
        "_menu_anytls_obfuscation",
        "_menu_mieru",
        "_menu_mieru_obfuscation",
        "_menu_trusttunnel",
        "_rotate_awg_obfuscation",
        "_show_plugin_clients",
        "_tune_awg_hardware",
    ),
}


__all__ = ["BINDER_SPECS", "FORWARD_GROUPS"]
